version: "2.4"

services:
  buildviz:
    volumes:
      - ./data:/buildviz/data
    image: cburgmer/buildviz

  sync:
    command: schedule buildviz.teamcity.sync "https://guest@teamcity.jetbrains.com" --project KotlinTools --buildviz http://buildviz:3000
    restart: always
    image: cburgmer/buildviz

  nginx:
    build: nginx
    ports:
      - "8080:8080"
    image: cburgmer/buildviz-nginx
