version: "2.4"

services:
  server:
    image: jetbrains/teamcity-server:2018.2.1
    volumes:
      - ./data:/data/teamcity_server/datadir
    ports:
      - "8111:8111"

  agent:
    image: jetbrains/teamcity-minimal-agent:2018.2.1
    restart: always
    environment:
      SERVER_URL: "http://server:8111"
